name: Scala CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Java ${{matrix.java}}
    strategy:
      matrix:
        java: ['adopt:1.11', 'temurin:1.11', 'temurin:1.17']
    steps:
    - uses: actions/checkout@v2
    - name: Setup Scala and Java
      uses: coursier/setup-action@v1
      with:
        jvm: ${{matrix.java}}
    - name: Start Postgres
      run: sh ./scripts/launch-postgres.sh
    - name: Run tests
      run: sbt +test
